### ISSUE TITLE
Incorrect format load issue.

### ISSUE THREAD

**Issue by bayganik** [sbarisic/RaylibGame#2]
Would you know why this issue comes up?  I down loaded your entire rep and compiled it.

System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=RaylibSharp
  StackTrace:
   at RaylibSharp.Raylib.InitWindow(Int32 width, Int32 height, String title)
   at RaylibTest.Engine.GameWindow..ctor(Int32 W, Int32 H, String Title) in C:\DevApps\RayLib\RaylibGame-main\RaylibTest\Engine\GameWindow.cs:line 19
   at RaylibTest.Program.Main(String[] args) in C:\DevApps\RayLib\RaylibGame-main\RaylibTest\Program.cs:line 22

**Comment by bayganik** [comment]
solved.  In case anyone else comes here.  I went and build the csharp codes as x86 (32 bit) application and it did the trick.

**Comment by sbarisic** [comment]
Yes, it is meant to be compiled as x64 (works) or x86 (not tested) and not AnyCPU.

Side note, i ported the voxel code into another engine which i'm working on from scratch and this repository might not be updated
https://github.com/sbarisic/libTech
